steps:
  - name: security-check
    command: docker run --rm -it -v "$PWD:$PWD" -w "$PWD" allthings/nsp
    branches: 'HEAD'

  - name: build
    command: bin/artifacts-build.sh
    artifact_paths: build/artifacts/*.tar.gz
    branches: '!HEAD'
    agents:
      queue: t2-large

  - wait

  - name: lint
    command: >
      bin/artifacts-download.sh &&
      bin/docker-node.sh yarn lint &&
      bin/docker-node.sh yarn security-check
    branches: '!HEAD'
    agents:
      queue: t2-large

  - name: test
    command: >
      bin/artifacts-download.sh &&
      rm -rf logs &&
      bin/test-ci.sh --update --log php,api,nginx,accounts
    artifact_paths: >
      test/logs/**/*.log
    branches: '!HEAD'
    agents:
      queue: t2-large

  - wait

  - name: release
    command: >
      bin/artifacts-download.sh &&
      git remote set-url origin https://github.com/allthings/node-sdk.git && 
      git checkout master &&
      git pull &&
      bin/docker-node.sh yarn semantic-release
    branches: 'master'
    agents:
      queue: t2-large
